import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Header from "../../MyComponents/Header/Header";
import Footer from "../../MyComponents/Footer/Footer";
import { Providers } from "./providers";
import { NextAppProvider } from "@toolpad/core/nextjs";
import LinearProgress from "@mui/material/LinearProgress";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import React from "react";
import { Navigation } from "@toolpad/core";

import { LayoutDashboardIcon } from "lucide-react";
import { TimelineOutlined } from "@mui/icons-material";
import FetchGlobalData from "../../MyComponents/GlobalComponents/FetchGlobalData";

const NAVIGATION: Navigation = [
  {
    kind: "header",
    title: "Main items",
  },
  {
    segment: "dashboard",
    title: "Dashboard",
    icon: <LayoutDashboardIcon />,
  },
  {
    segment: "dashboard/orders",
    title: "Orders",
    icon: <TimelineOutlined />,
  },
  {
    segment: "dashboard/addProduct",
    title: "Add Product",
    icon: <TimelineOutlined />,
  },
];

const BRANDING = {
  title: "Hush Catties",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider options={{ enableCssLayer: false }}>
          <React.Suspense fallback={<LinearProgress />}>
            <NextAppProvider navigation={NAVIGATION} branding={BRANDING}>
              <Providers>
                <Header />
                {children}
                <Footer />
                <Toaster />
                <FetchGlobalData />
              </Providers>
            </NextAppProvider>
          </React.Suspense>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
